# Path to Aithon library
AITHON_LIBRARY = ../AithonLibrary

# User source files
USERSRC = $(wildcard ./*.c) $(wildcard Tests/*.c)

# User include paths
USERINC = ./ Tests/

# Target board revision. Either r4 or v01
BOARD_REV = v01

# Include the primary Aithon makefile
include $(AITHON_LIBRARY)/Aithon.mk