# Path to Aithon library
AITHON_LIBRARY = ../AithonLibrary

# User source files
USERSRC = $(wildcard ./*.c) $(wildcard Tests/*.c)

# User include paths
USERINC = ./ Tests/

# Include the primary Aithon makefile
include $(AITHON_LIBRARY)/Aithon.mk