# Path to Aithon library
AITHON_LIBRARY = ../../AithonLibrary

# User source files
USERFOLDER = ./
USERSRC = $(USERFOLDER)/$(wildcard *.c)

# User include paths
USERINC = ./

# Include the primary Aithon makefile
include $(AITHON_LIBRARY)/Aithon.mk
