# Path to Aithon library
AITHON_LIBRARY = ../AithonLibrary

# User source files
USERSRC = $(wildcard *.c)

# User include paths
USERINC = ./

# This is the bootloader so goes at the start of the FLASH
IS_BOOTLOADER = yes

# Target board revision. Either r4 or v01
BOARD_REV = r4

# Include the primary Aithon makefile
include $(AITHON_LIBRARY)/Aithon.mk