# Path to Aithon library
AITHON_LIBRARY = /Users/jseng/aithon/AithonLibrary

# User source files
USERFOLDER = ./
USERSRC =$(addprefix $(USERFOLDER),$(wildcard *.c))

# User include paths
USERINC = ./

# Include the primary Aithon makefile
include $(AITHON_LIBRARY)/Aithon.mk
