# Specify the COM port for programming
COM_PORT = COM5

# Path to Aithon library
AITHON_LIBRARY = ../AithonLibrary

# User source files
USERSRC = $(wildcard *.c)

# User include paths
USERINC = ./

# Include the primary Aithon makefile
include $(AITHON_LIBRARY)/Aithon.mk